### ISSUE TITLE
Example code for Task creation

### ISSUE THREAD

**Issue by sam-tj** [PetoiCamp/OpenCat#33]
Is there a sample code which integrates the Digital / Analog pins with the base code (OpenCat.ino)

For example, 
The robot should be moving forward but should stop when ultrasonic detects an object within certain range. This must be done using Arduino IDE (C++) but as per the source codes, I couldn't find an example for such integration of io pins with per-defined skills.

**Comment by borntoleave** [comment]
I just updated OpenCat.ino to include a simple demo that triggers skills with an input pin.
