### ISSUE TITLE
opencat app bug : Team: 网络连接已中断。

### ISSUE THREAD

**Issue by xiguaABei** [PetoiCamp/OpenCat#62]
today ，i use opencat app , when i send message i shows a toast Team: 网络连接已中断。

**Comment by JasonWong08** [comment]
> today ，i use opencat app , when i send message i shows a toast Team: 网络连接已中断。

what's the app? Petoi Desktop App or smartphone app?

**Comment by borntoleave** [comment]
> today ，i use opencat app , when i send message i shows a toast Team: 网络连接已中断。

It appears to be another app that's using our OpenCat name.
