### ISSUE TITLE
pyUI/commonVar.py uses wrong paths for Linux

### ISSUE THREAD

**Issue by nrwahl2** [PetoiCamp/OpenCat#70]
```
elif platform.system() == "Linux":    # for Linux
    sys.path.append('/usr/share/petoi-opencat/serialMaster/')
    resourcePath = '/usr/share/petoi-opencat/resources/'
    releasePath = '/usr/share/petoi-opencat/release/'
```

There's no reason these directories would be subdirectories of `/usr/share/petoi-opencat`. There's no installation procedure for Linux that would put them there. The Petoi documentation says to run `python3 UI.py` from a source checkout. There's no `make install` and there's no package (RPM, Pip, or otherwise).

**Comment by JasonWong08** [comment]
Thanks for your feedback. These scripts are used for the Linux user who has installed the desktop app before. We will fix this issue in the next release soon.

**Comment by nrwahl2** [comment]
Thanks @JasonWong08. I may have overlooked it, or it might be legacy -- I didn't see a procedure for installing the desktop app on Linux, that would install files in standard directories like `/usr/share`.
