### ISSUE TITLE
Is there a way to disable the beep sound?

### ISSUE THREAD

**Issue by Kakcalu13** [PetoiCamp/OpenCat#76]
It beeps so much that it disturbed my team lol

**Comment by borntoleave** [comment]
Yes, you can send a single 'b' to the serial port mute/unmute the beeps. 
<img width="845" alt="Screenshot 2024-02-17 at 11 59 36"
 src="https://github.com/PetoiCamp/OpenCat/assets/9747608/52f2d1b7-d1d2-4e63-9156-043898b9b51a">

<img width="1005" alt="Screenshot 2024-02-17 at 12 01 03" src="https://github.com/PetoiCamp/OpenCat/assets/9747608/f816f047-871f-4c2a-aa4e-a78504b33c54">


You can even delete the lines with beep() function.
<img width="809" alt="Screenshot 2024-02-17 at 12 03 22" src="https://github.com/PetoiCamp/OpenCat/assets/9747608/4048dd3a-c605-40bb-857c-35ec2e3ff996">
